[package]
name = "bifrost-imap"
description = "IMAP Account implementation for bifrost"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
homepage = "https://github.com/folknor/bifrost"
license.workspace = true
edition.workspace = true

keywords = ["email", "imap", "async", "tokio"]
categories = ["email", "network-programming", "asynchronous"]

[lib]
doctest = false

[lints]
workspace = true

[features]
default = []

[dependencies]
base64 = { workspace = true }
bifrost-types = { path = "../types" }
bifrost-net = { path = "../net" }
bifrost-caldav = { path = "../caldav" }
bifrost-carddav = { path = "../carddav" }
bifrost-sasl = { path = "../sasl" }
bifrost-smtp = { path = "../smtp", features = ["tokio"] }
bytes = { workspace = true }
chrono = { workspace = true }
encoding_rs = "0.8"
flate2 = "1"
futures = { workspace = true }
getrandom = { workspace = true }
native-tls = { workspace = true }
nom = { workspace = true }
socket2 = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "io-util", "net", "time", "sync", "macros"] }
tokio-native-tls = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true, features = ["std"] }
zeroize = { workspace = true }

[dev-dependencies]
pretty_assertions = "1.2"
proptest = "1"
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "test-util"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
