[package]
name = "bifrost-caldav"
description = "CalDAV Account implementation for bifrost"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage = "https://github.com/folknor/bifrost"
keywords = ["calendar", "caldav", "icalendar", "webdav"]
categories = ["email", "network-programming", "asynchronous"]

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
base64 = { workspace = true }
bifrost-net = { path = "../net" }
bifrost-types = { path = "../types" }
bytes = { workspace = true }
caldata = { workspace = true }
jiff = { workspace = true }
futures = { workspace = true }
quick-xml = "0.41.0"
reqwest = { workspace = true, features = ["native-tls"] }
uuid = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
