[package]
name = "bifrost-gmail"
description = "Gmail API client for Rust"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage = "https://github.com/folknor/bifrost"
keywords = ["email", "gmail", "google", "mail"]
categories = ["email", "network-programming", "asynchronous"]

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
base64 = { workspace = true }
bifrost-types = { path = "../types" }
blake3 = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
reqwest = { workspace = true, features = ["json", "native-tls"] }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync", "time"] }
tokio-util = { workspace = true }
urlencoding = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
