[package]
name = "imap-proto"
version = "0.17.0"
description = "IMAP protocol parser and data structures"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
keywords = ["imap", "email"]
categories = ["email", "network-programming", "parser-implementations"]
homepage = "https://github.com/folknor/bifrost"

[lib]
doctest = false

[dependencies]
nom = "8.0.0"

[dev-dependencies]
assert_matches = "1.3"
