[package]
name = "bifrost-carddav"
description = "CardDAV Account implementation for bifrost"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage = "https://github.com/folknor/bifrost"
keywords = ["contacts", "carddav", "vcard", "webdav"]
categories = ["email", "network-programming", "asynchronous"]

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
bifrost-types = { path = "../types" }
